### ISSUE TITLE
`text/event-stream` should not be compressible

### ISSUE THREAD

**Issue by pmuellr** [jshttp/compressible#16]
At least as of tonight, sending server-sent events, aka EventSource, turns out not to be readable by the browser if compressed.  Seems - ya, I can understand that, I guess.  Maybe if you send enough text after your event the browser's decompressor could handle it - but in practice not even that works today.

As I'm using `compressible` indirectly via a `app.use(compression)` in my express app today, this means my EventSource in the browser never gets events.

I believe adding `text/event-stream` as an un-compressible content type should fix this.  Working around it now by adding a `filter` on the `app.use(compression)` invocation.

I'll give it a try soon, and if it works, send along a PR ...

**Comment by dougwilson** [comment]
Hi, that content type is compressible, so we're not going to add it to the list. Have you looked at the example in the README for using a compressed event stream? Did that not work?

**Comment by dougwilson** [comment]
The readme of the compression module, that is.

**Comment by dougwilson** [comment]
Anyway, now that I'm at a computer I can extend my response:

I don't think that is an issue with this library. The contents of `text/event-stream` are text, which is compressible. This module is just saying which types represent compressible content, not taking into account how the content is going to be used. For example, the same argument can be made about `text/html`, that it should not be compressed because you want to send out the top of the HTML page in one chunk, then do some database work and then the rest of the page (such that the web browser can spend that time fetching the resources referenced in the top of the page).

The `compression` module itself offers you three different solutions for you:

1. Follow the example in https://github.com/expressjs/compression#server-sent-events
2. Add the response header `Cache-Control: no-transform` to your SSE response as noted in https://github.com/expressjs/compression#compressionoptions
3. Specify a `filter` option that works best for you as mentioned in https://github.com/expressjs/compression#filter (and there is an example of just tweaking the default filter at https://github.com/expressjs/compression#filter-1).

**Comment by pmuellr** [comment]
Thanks Doug, it does in fact work fine with an additional `res.flush()` - I should have read through more of the README ...
